#!/usr/bin/env python

from optparse import OptionParser

# import binascii
import struct
import crcmod
import os

def get_checksum(data):
    crc32 = crcmod.Crc(0x104c11db7, initCrc=0xFFFFFFFF, rev=False)
    for i in xrange(0, ((len(data) - 1) / 4)):
        item = struct.unpack_from("<I", data, i * 4)[0]
        crc32.update(struct.pack(">I", item))

    return crc32.crcValue

def get_stm32_checksum(data):
    crc32 = crcmod.Crc(0x104c11db7, initCrc=0xFFFFFFFF, rev=False)
    for word in data:
        item = struct.unpack("<I", word)[0]
        crc32.update(struct.pack(">I", item))

    return crc32.crcValue

if __name__ == "__main__":
    parser = OptionParser(usage="usage: %prog [options] <FW file>")
    parser.add_option("-a", "--add",
                      action  ="store_true",
                      dest    ="add_suffix",
                      default = False,
                      help    ="Add STFUBoot prefix to <file>")

    parser.add_option("-D", "--delete",
                      action  ="store_true",
                      dest    ="delete_suffix",
                      default = False,
                      help    ="Delete STFUBoot prefix from <file>")

    (options, args) = parser.parse_args()

    image_name = args[0]
    image_file = open(image_name, 'rb')
    image_data = image_file.read()

    img_nm_i = image_name[:-4] + "_interim.bin"

    file_size = os.path.getsize(image_name)
    interim_file = open(img_nm_i, 'w')
    interim_file.write(image_data)

    interim_file.write(struct.pack("<I", 0))
    interim_file.close()

    file_crc  = get_checksum(image_data)

    image_file.close()

    img_nm = image_name[:-4] + "_sliced.bin"
    img_nm2 = image_name[:-4] + "_sliced2.bin"
    new_image = open(img_nm2, 'w')

    new_image.write(struct.pack("<I", file_size))
    new_image.seek(504)
    new_image.write(struct.pack("<I", file_crc))
    new_image.write(struct.pack("<I", 0))

    new_image.close()
    new_image = open(img_nm2, 'r')
    tst = new_image.read()
    new_image.close()

    new_image= open(img_nm, 'w')
    new_image.seek(0)
    new_image.write(struct.pack("<I", file_size))
    new_image.seek(504)
    new_image.write(struct.pack("<I", file_crc))
    new_image.write(struct.pack("<I", get_checksum(tst)))

    print "Filesize:", file_size
    print "File CRC:", str(hex(file_crc))
    print "File CRC:", str(file_crc)
    print "Header CRC:", str(hex(get_checksum(tst)))
    print "Header CRC:", str(get_checksum(tst))
    new_image.write(image_data)
    new_image.close()

    # if options.delete_suffix:
    #     pass
    # elif options.add_suffix:

    #     print image.read()

    # app_bin = open('app.bin', 'rb')
    # app_elf = ELFFile(open('app.elf', 'rb'))
    # _text_data = app_elf.get_section_by_name('.text').data()

    # text_area_size = len(_text_data) / 4 #size of text area in words

    # loader_data, application_data = split_fw(app_bin)
    # write_loader(loader_data)

    # checksum = get_checksum(_text_data)
    # write_application(application_data, checksum, text_area_size)

    # print "Application and Loader firmware hunks written"
    # print "Application Checksum:", str(hex(checksum))[:-1]
    # app_bin.close()
